-- 1. Users table (for both regular users and admins)
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    user_type VARCHAR2(10) DEFAULT 'user' CHECK (user_type IN ('user', 'admin')),
    phone_number VARCHAR2(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active NUMBER(1) DEFAULT 1
);

-- 2. Rooms table
CREATE TABLE rooms (
    room_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR2(10) UNIQUE NOT NULL,
    room_type VARCHAR2(50) NOT NULL,
    description VARCHAR2(500),
    capacity NUMBER(2) NOT NULL,
    price_per_night NUMBER(10,2) NOT NULL,
    amenities CLOB,
    status VARCHAR2(20) DEFAULT 'available' CHECK (status IN ('available', 'occupied', 'maintenance')),
    created_by NUMBER, -- user_id of admin who created
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_rooms_created_by FOREIGN KEY (created_by) REFERENCES users(user_id)
);

-- 3. Bookings table
CREATE TABLE bookings (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    room_id NUMBER NOT NULL,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL,
    total_nights NUMBER(3) NOT NULL,
    total_price NUMBER(10,2) NOT NULL,
    booking_status VARCHAR2(20) DEFAULT 'pending' CHECK (booking_status IN ('pending', 'confirmed', 'cancelled', 'completed')),
    payment_status VARCHAR2(20) DEFAULT 'unpaid' CHECK (payment_status IN ('unpaid', 'partial', 'paid')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    notes VARCHAR2(500),
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_bookings_room FOREIGN KEY (room_id) REFERENCES rooms(room_id)
);

-- 4. Payments table
CREATE TABLE payments (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id NUMBER NOT NULL,
    amount_paid NUMBER(10,2) NOT NULL,
    payment_method VARCHAR2(50),
    transaction_id VARCHAR2(100),
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    payment_type VARCHAR2(20) DEFAULT 'booking' CHECK (payment_type IN ('booking', 'additional')),
    status VARCHAR2(20) DEFAULT 'success' CHECK (status IN ('success', 'failed', 'pending')),
    notes VARCHAR2(500),
    CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id)
);

-- 5. Audit log table (to track admin actions)
CREATE TABLE audit_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER,
    action_type VARCHAR2(50) NOT NULL,
    table_name VARCHAR2(50) NOT NULL,
    record_id NUMBER,
    old_values CLOB,
    new_values CLOB,
    ip_address VARCHAR2(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_admin FOREIGN KEY (admin_id) REFERENCES users(user_id)
);

-- Create indexes for better performance
CREATE INDEX idx_bookings_user ON bookings(user_id);
CREATE INDEX idx_bookings_dates ON bookings(check_in_date, check_out_date);
CREATE INDEX idx_rooms_status ON rooms(status);
CREATE INDEX idx_payments_booking ON payments(booking_id);